print('Hello World')
print('Whats you name')
name =input('> ')
print('Its nice to meet you, ' + name)
print('the length of you name is: ')
print(len(name))
print('whats you age')
age = input('> ')
print('You will be ' + str(int(age) + 1) + ' in a year')